export const ERROR_CODES = {
  OK: "OK",
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_API_KEY: "INVALID_API_KEY",
  LICENSE_NOT_FOUND: "LICENSE_NOT_FOUND",
  INVALID_LICENSE_KEY: "INVALID_LICENSE_KEY",
  LICENSE_EXPIRED: "LICENSE_EXPIRED",
  LICENSE_SUSPENDED: "LICENSE_SUSPENDED",
  DOMAIN_MISMATCH: "DOMAIN_MISMATCH",
  DOMAIN_LIMIT_EXCEEDED: "DOMAIN_LIMIT_EXCEEDED",
  PLUGIN_NOT_FOUND: "PLUGIN_NOT_FOUND",
  PLUGIN_MISMATCH: "PLUGIN_MISMATCH",
  PLUGIN_NOT_ALLOWED: "PLUGIN_NOT_ALLOWED",
  CONTRACT_NOT_FOUND: "CONTRACT_NOT_FOUND",
  CONTRACT_EXPIRED: "CONTRACT_EXPIRED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const SUCCESS_CODES = {
  HEALTHY: "HEALTHY",
  LICENSE_ACTIVE: "LICENSE_ACTIVE",
  LICENSE_DEACTIVATED: "LICENSE_DEACTIVATED",
  VERSION_CHECKED: "VERSION_CHECKED",
  PLUGIN_LIST_FOUND: "PLUGIN_LIST_FOUND",
  DOWNLOAD_TOKEN_CREATED: "DOWNLOAD_TOKEN_CREATED",
  CONTRACT_FOUND: "CONTRACT_FOUND",
  LOG_CREATED: "LOG_CREATED"
} as const;

export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES];

export const API_CODES = {
  ...ERROR_CODES,
  ...SUCCESS_CODES
} as const;

export type ApiCode = (typeof API_CODES)[keyof typeof API_CODES];
