export const KINTONE_TABLES = {
  CUSTOMERS: "customers",
  CONTRACTS: "contracts",
  LICENSES: "licenses",
  PLUGINS: "plugins",
  PLUGIN_VERSIONS: "plugin_versions",
  REGISTERED_DOMAINS: "registered_domains",
  AUTH_LOGS: "auth_logs",
  DOWNLOAD_LOGS: "download_logs",
  API_SETTINGS: "api_settings"
} as const;

export type KintoneTable = (typeof KINTONE_TABLES)[keyof typeof KINTONE_TABLES];

export const KINTONE_FIELD_CODES = {
  customers: {
    customerId: "customer_id",
    companyName: "company_name",
    companyKana: "company_kana",
    contactName: "contact_name",
    contactEmail: "contact_email",
    phoneNumber: "phone_number",
    postalCode: "postal_code",
    address: "address",
    customerStatus: "customer_status",
    wordpressUserId: "wordpress_user_id",
    registeredDate: "registered_date",
    remarks: "remarks",
    createdAt: "created_at",
    updatedAt: "updated_at"
  },
  contracts: {
    contractId: "contract_id",
    customerId: "customer_id",
    companyName: "company_name",
    planType: "plan_type",
    contractStatus: "contract_status",
    contractStart: "contract_start",
    contractEnd: "contract_end",
    billingCycle: "billing_cycle",
    contractAmount: "contract_amount",
    maxDomainCount: "max_domain_count",
    maxPluginCount: "max_plugin_count",
    autoRenewalFlag: "auto_renewal_flag",
    remarks: "remarks",
    createdAt: "created_at",
    updatedAt: "updated_at"
  },
  licenses: {
    licenseId: "license_id",
    licenseKey: "license_key",
    licenseKeyHash: "license_key_hash",
    customerId: "customer_id",
    contractId: "contract_id",
    pluginId: "plugin_id",
    licenseStatus: "license_status",
    issueDate: "issue_date",
    expireDate: "expire_date",
    maxDomainCount: "max_domain_count",
    currentDomainCount: "current_domain_count",
    lastAuthDatetime: "last_auth_datetime",
    lastAuthResult: "last_auth_result",
    memo: "memo",
    createdAt: "created_at",
    updatedAt: "updated_at"
  },
  plugins: {
    pluginId: "plugin_id",
    pluginCode: "plugin_code",
    pluginName: "plugin_name",
    pluginDescription: "plugin_description",
    pluginCategory: "plugin_category",
    publishStatus: "publish_status",
    latestVersion: "latest_version",
    forceUpdateVersion: "force_update_version",
    supportUrl: "support_url",
    manualUrl: "manual_url",
    createdAt: "created_at",
    updatedAt: "updated_at"
  },
  pluginVersions: {
    versionId: "version_id",
    pluginId: "plugin_id",
    version: "version",
    releaseStatus: "release_status",
    releaseDate: "release_date",
    pluginZip: "plugin_zip",
    fileName: "file_name",
    fileSize: "file_size",
    checksum: "checksum",
    releaseNote: "release_note",
    isLatest: "is_latest",
    isForceUpdate: "is_force_update",
    createdAt: "created_at",
    updatedAt: "updated_at"
  },
  registeredDomains: {
    domainId: "domain_id",
    licenseId: "license_id",
    licenseKey: "license_key",
    kintoneDomain: "kintone_domain",
    appId: "app_id",
    environment: "environment",
    domainStatus: "domain_status",
    registeredAt: "registered_at",
    lastAccessAt: "last_access_at",
    deactivatedAt: "deactivated_at",
    remarks: "remarks"
  },
  authLogs: {
    logId: "log_id",
    authDatetime: "auth_datetime",
    eventType: "event_type",
    resultStatus: "result_status",
    licenseId: "license_id",
    licenseKey: "license_key",
    pluginId: "plugin_id",
    pluginVersion: "plugin_version",
    kintoneDomain: "kintone_domain",
    appId: "app_id",
    ipAddress: "ip_address",
    userAgent: "user_agent",
    errorCode: "error_code",
    message: "message",
    createdAt: "created_at"
  },
  downloadLogs: {
    downloadLogId: "download_log_id",
    downloadDatetime: "download_datetime",
    customerId: "customer_id",
    pluginId: "plugin_id",
    versionId: "version_id",
    version: "version",
    downloadToken: "download_token",
    tokenExpireAt: "token_expire_at",
    downloadResult: "download_result",
    ipAddress: "ip_address",
    userAgent: "user_agent",
    message: "message"
  },
  apiSettings: {
    settingKey: "setting_key",
    settingName: "setting_name",
    settingValue: "setting_value",
    settingType: "setting_type",
    enabledFlag: "enabled_flag",
    description: "description",
    updatedAt: "updated_at"
  }
} as const;
